### PR TITLE
Permit requirements to be x or higher

### PR DESCRIPTION
**Pull request by eode**
* Allow higher versions of Sphinx
* Lower versions of Sphinx may work, but haven't been tested
* Sphinx limited to version < 2
* All other libraries unrestricted, but should later be restricted if breaking changes are made,
  or if they are found to use semantic versioning and can be range-limited, as done with Sphinx

### CODE REVIEW

**Review by clayrisser — APPROVED** [review]

**Comment by clayrisser** [comment]
I will submit the new pypi module later today.

**Comment by inuwashi** [comment]
Thank you so much for this!!

**Comment by clayrisser** [comment]
Absolutely! I pushed this merge to `v0.1.7`.

**Comment by inuwashi** [comment]
FYI - your librapay account is not setup to take money :)

**Comment by clayrisser** [comment]
@inuwashi thanks for the heads up. I just set it up to accept money. Any donation to keep me going is very much appreciated.

**Comment by inuwashi** [comment]
Enjoy the coffee

**Pull request merged**
